// RESEARCH: 
//    boids implmentation : https://github.com/hughsk/boids/blob/master/index.js
//                          https://vanhunteradams.com/Pico/Animal_Movement/Boids-algorithm.html
//                          https://github.com/michaelmoreno/boids-algorithm    

// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "behavior",
  id: "piranha305_boids",
  name: "boids",
  version: "1.0.0.0",
  category:
    // "attributes",
    // "movements",
    // "other",
    "general",
  author: "piranha305",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Description",
  // icon: "icon.svg", // defaults to "icon.svg" if omitted
  // addonUrl: "https://www.construct.net/en/make-games/addons/####/XXXX", // displayed in auto-generated docs
  // githubUrl: "https://github.com/skymen/XXXX", // displays latest release version in auto-generated docs
  fileDependencies: [
    {
      filename: "quadtree.js",
      type: "inline-script",
    }
    /*
    {
      filename: "filename.js", // no need to include "c3runtime/" prefix
      type:
        "copy-to-output"
        "inline-script"
        "external-dom-script"
        "external-runtime-script"
        "external-css"

      // for copy-to-output only
      // fileType: "image/png"
    }
    */
  ],
  info: {
    Set: {
      IsOnlyOneAllowed: false,
      CanBeBundled: true,
      IsDeprecated: false,
    },
  },
  properties: [
    {
      type: "check",
      id: "enabled",
      name: "Enabled",
      options: {
        initialValue: true,
      },
      desc: "Enable or disable the boids behavior.",
    },
    {
      type: "float",
      id: "maxSpeed",
      name: "Max Speed",
      options: {
        initialValue: 500
      },
      desc: "Maximum speed of each boid unit.",
    },
    {
      type: "float",
      id: "maxForce",
      name: "MaxForce",
      options: {
        initialValue: 1
      },
      desc: "Maximum steering force of each boid unit.",
    },
    {
      type: "check",
      id: "setAngle",
      name: "Set Angle",
      options: {
        initialValue: false
      },
      desc: "Set angle of each boid unit to match its movement direction.",
    },
    {
      type: "float",
      id: "separationDistance",
      name: "Separation Distance",
      options: {
        initialValue: 30
      },
      desc: "Distance to keep away from other boids.",
    },
    {
      type: "float",
      id: "separationPriority",
      name: "Separation Priority",
      options: {
        initialValue: 1
      },
      desc: "Priority of the separation behavior.",
    },
    {
      type: "float",
      id: "alignmentPriority",
      name: "Alignment Priority",
      options: {
        initialValue: 10
      },
      desc: "Priority of the alignment behavior.",
    },
    {
      type: "float",
      id: "cohesionPriority",
      name: "Cohesion Priority",
      options: {
        initialValue: 10
      },
      desc: "Priority of the cohesion behavior.",
    },
    {
      type: "combo",
      id: "flockNeighborsStrategy",
      name: "Flocking Neighbors Strategy",
      options: {
        initialValue: "all",
        items: [
          { all: "All" },
          { distance: "Distance" },
          { los: "Line of Sight" },
          { quadtree: "Quadtree" },
        ],
      },
    },
    {
      type: "float",
      id: "flockNeighborDistance",
      name: "Flocking Neighbor Distance",
      options: {
        initialValue: 100
      },
      desc: "Distance used by the distance - neighbors strategy.",
    }
    /*
    {
      type:
        "integer"
        "float"
        "percent"
        "text"
        "longtext"
        "check"
        "font"
        "combo"
        "group"
        "link"
        "info"

      id: "property_id",
      options: {
        initialValue: 0,
        interpolatable: false,

        // minValue: 0, // omit to disable
        // maxValue: 100, // omit to disable

        // for type combo only
        // items: [
        //   {itemId1: "item name1" },
        //   {itemId2: "item name2" },
        // ],

        // dragSpeedMultiplier: 1, // omit to disable

        // for type link only
        // linkCallback: `function(instOrObj) {}`,
        // linkText: "Link Text",
        // callbackType:
        //   "for-each-instance"
        //   "once-for-type"

        // for type info only
        // infoCallback: `function(inst) {}`,
      },
      name: "Property Name",
      desc: "Property Description",
    }
    */
  ],
  aceCategories: {
    // follows the format id: langName
    // in the ACEs refer to categories using the id, not the name
    general: "General",
  },
  Acts: {
    SetEnabled: {
      category: "general",
      forward: "SetEnabled",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      params: [
        {
          id: "enabled",
          name: "Enabled",
          desc: "Enabled",
          type: "boolean",
          value: true,
        },
      ],
      listName: "Set {my} enabled to {0}",
      displayText: "{my}: Set enabled to {0}",
      description: "Set enabled",
    },
    SetSeperationPriority: {
      category: "general",
      forward: "SetSeperationPriority",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      params: [
        {
          id: "priority",
          name: "Priority",
          desc: "Priority",
          type: "number",
          value: 1,
        },
      ],
      listName: "Set {my} seperation priority to {0}",
      displayText: "{my}: Set seperation priority to {0}",
      description: "Set seperation priority",
    },
    SetAlignmentPriority: {
      category: "general",
      forward: "SetAlignmentPriority",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      params: [
        {
          id: "priority",
          name: "Priority",
          desc: "Priority",
          type: "number",
          value: 1,
        },
      ],
      listName: "Set {my} alignment priority to {0}",
      displayText: "{my}: Set alignment priority to {0}",
      description: "Set alignment priority",
    },
    SetCohesionPriority: {
      category: "general",
      forward: "SetCohesionPriority",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      params: [
        {
          id: "priority",
          name: "Priority",
          desc: "Priority",
          type: "number",
          value: 1,
        },
      ],
      listName: "Set {my} cohesion priority to {0}",
      displayText: "{my}: Set cohesion priority to {0}",
      description: "Set cohesion priority",
    },
    FlockToTarget: {
      category: "general",
      forward: "FlockToTarget",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      params: [
        {
          id: "targetX",
          name: "Target X",
          desc: "Target X",
          type: "number",
          value: 0,
        },
        {
          id: "targetY",
          name: "Target Y",
          desc: "Target Y",
          type: "number",
          value: 0,
        }
      ],
      listName: "Flock",
      displayText: "{my}: Flock to [i]{0}[/i], [i]{1}[/i]",
      description: "Flock",
    },
    FlockRandom: {
      category: "general",
      forward: "FlockRandom",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      params: [],
      listName: "Flock Random",
      displayText: "{my}: Flock random",
      description: "Flock in random directions",
    }
    /*
    SampleAction: {
      // The category of the action as it appears in the add action dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this action
      // Cases where you might not want this are:
      // 1- If the action params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the action in the add action dialog
      highlight: true,

      // Set to true to hide the action in the interface. False by default if not specified.
      deprecated: false,

      // Marks the action as async. Defaults to false if not specified.
      isAsync: false,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the action as it appears in the add action dialog
      listName: "Sample Action",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      // You can also use the {my} tag to include the behavior icon and name.
      displayText: "{my}: Sample action [i]{0}[/i]",

      // The description of the action as it appears in the add action dialog
      description: "This is a sample action",
    },
    */
  },
  Cnds: {
    /*
    SampleCondition: {
      // The category of the action as it appears in the add condition dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this condition
      // Cases where you might not want this are:
      // 1- If the condition params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the condition in the add condition dialog
      highlight: true,

      // Set to true to hide the condition in the interface. False by default if not specified.
      deprecated: false,

      // special conditions properties. These can all be omitted, and they will default to the following values:
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the condition as it appears in the add condition dialog
      listName: "Sample Condition",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      // You can also use the {my} tag to include the behavior icon and name.
      displayText: "{my}: Sample condition [i]{0}[/i]",

      // The description of the condition as it appears in the add condition dialog
      description: "This is a sample condition",
    },
    */
  },
  Exps: {
    /*
    SampleExpression: {
      // The category of the action as it appears in the expression picker
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this expression
      // Cases where you might not want this are:
      // 1- If you don't want it to appear in the script interface
      // 2- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the expression in the expression picker
      highlight: true,

      // Set to true to hide the expression in the interface. False by default if not specified.
      deprecated: false,

      // The type of the expression.
      returnType:
        - "string"
        - "number"
        - "any" // must be either string or number

      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
        },
      ],

      // The description of the expression as it appears in the expression picker
      description: "This is a sample expression",
    },
    */
  },
};
